// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

using System.Threading;
using System.Threading.Tasks;
using VehicleTracke.VehicleSimulator.FunctionTrigger.PingReceiverServiceClient.Models;

namespace VehicleTracke.VehicleSimulator.FunctionTrigger.PingReceiverServiceClient
{
    /// <summary>
    /// Extension methods for PingReceiverService.
    /// </summary>
    public static partial class PingReceiverServiceExtensions
    {
            /// <summary>
            /// Ping
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='version'>
            /// </param>
            /// <param name='pingViewModel'>
            /// </param>
            public static void Post(this IPingReceiverService operations, string version, PingViewModel pingViewModel = default(PingViewModel))
            {
                operations.PostAsync(version, pingViewModel).GetAwaiter().GetResult();
            }

            /// <summary>
            /// Ping
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='version'>
            /// </param>
            /// <param name='pingViewModel'>
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task PostAsync(this IPingReceiverService operations, string version, PingViewModel pingViewModel = default(PingViewModel), CancellationToken cancellationToken = default(CancellationToken))
            {
                (await operations.PostWithHttpMessagesAsync(version, pingViewModel, null, cancellationToken).ConfigureAwait(false)).Dispose();
            }

    }
}
