// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

using Newtonsoft.Json;

namespace VehicleTracke.VehicleSimulator.FunctionTrigger.PingReceiverServiceClient.Models
{
    public partial class PingViewModel
    {
        /// <summary>
        /// Initializes a new instance of the PingViewModel class.
        /// </summary>
        public PingViewModel()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the PingViewModel class.
        /// </summary>
        public PingViewModel(System.Guid? id = default(System.Guid?), string vehicleId = default(string), System.DateTime? pingTime = default(System.DateTime?))
        {
            Id = id;
            VehicleId = vehicleId;
            PingTime = pingTime;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "id")]
        public System.Guid? Id { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "vehicleId")]
        public string VehicleId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "pingTime")]
        public System.DateTime? PingTime { get; set; }

    }
}
